const express=require('express');
const session=require('express-session');
const fs=require('fs');
const path=require('path');
const app=express();
const PORT=process.env.PORT||10000;
const DB=path.join(__dirname,'data','db.json');
const readDB=()=>JSON.parse(fs.readFileSync(DB,'utf8'));
const writeDB=d=>fs.writeFileSync(DB,JSON.stringify(d,null,2));
app.use(express.json({limit:'100kb'}));
app.use(express.urlencoded({extended:true}));
app.use(session({secret:process.env.SESSION_SECRET||'change-me',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:1000*60*60*8}}));
app.use(express.static(path.join(__dirname,'public')));
app.get('/admin',(req,res)=>res.redirect('/admin-login.html'));
app.get('/admin/login',(req,res)=>res.redirect('/admin-login.html'));
const admin=(req,res,next)=>req.session.admin?next():res.status(401).json({error:'Требуется вход'});
app.get('/api/public',(req,res)=>{const d=readDB();res.json({reviews:d.reviews,settings:d.settings})});
app.post('/api/applications',(req,res)=>{const {name,contact,plan,message='',template=''}=req.body||{};if(!name||!contact||!plan)return res.status(400).json({error:'Заполните имя, контакт и тариф'});const d=readDB();const item={id:Date.now().toString(36)+Math.random().toString(36).slice(2,7),name:String(name).slice(0,100),contact:String(contact).slice(0,150),plan:String(plan).slice(0,120),template:String(template).slice(0,120),message:String(message).slice(0,1000),createdAt:new Date().toISOString()};d.applications.unshift(item);writeDB(d);res.json({ok:true,item})});
app.post('/api/login',(req,res)=>{const u=process.env.ADMIN_USER||'admin';const p=process.env.ADMIN_PASSWORD||'change-me';if(req.body.username===u&&req.body.password===p){req.session.admin=true;return res.json({ok:true})}res.status(401).json({error:'Неверный логин или пароль'})});
app.post('/api/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get('/api/me',(req,res)=>res.json({admin:!!req.session.admin}));
app.get('/api/admin/data',admin,(req,res)=>{const d=readDB();res.json(d)});
app.post('/api/admin/reviews',admin,(req,res)=>{const {name,role='',text}=req.body||{};if(!name||!text)return res.status(400).json({error:'Заполните имя и текст'});const d=readDB();d.reviews.unshift({id:Date.now().toString(36),name:String(name).slice(0,100),role:String(role).slice(0,120),text:String(text).slice(0,800),createdAt:new Date().toISOString()});writeDB(d);res.json({ok:true})});
app.delete('/api/admin/reviews/:id',admin,(req,res)=>{const d=readDB();d.reviews=d.reviews.filter(x=>x.id!==req.params.id);writeDB(d);res.json({ok:true})});
app.delete('/api/admin/applications/:id',admin,(req,res)=>{const d=readDB();d.applications=d.applications.filter(x=>x.id!==req.params.id);writeDB(d);res.json({ok:true})});
app.listen(PORT,()=>console.log('KLN STUDIO running on port '+PORT));
